### ISSUE TITLE
Update the MemoryManager API so it can be used in conjunction with NIO to provide efficient buffer management

### ISSUE THREAD

**Issue by chirino** [raffaeleguidi/DirectMemory#49]
If MemoryManager implemented something like a  `ByteBuffer allocate(int size)` then I could be used to directly transfer data to/from Files and Sockets without having to first copy them to a byte[].

**Comment by raffaeleguidi** [comment]
First of all it should be allocateDirect() and then
ByteBuffer.allocateDirect() is a performance bottleneck - it is called just
once during the initialization phase right to address this issue.
sun.Unsafe could offer benefits for this approach instead

**Comment by chirino** [comment]
I think you mis-understand me.  I don't want to allocation new direct byte buffers.  I want `ByteBuffer allocate(int size)` to allocate a slice of the existing OffHeapMemoryBuffers that have been allocated.

**Comment by raffaeleguidi** [comment]
Uhm but allocate() is a static method that (quote from [1]) "Allocates a
new direct byte buffer"... I'm sure I am missing something (sorry, I'm
getting old :P) - but maybe you could write a small gist to better explain
what you mean

Ciao,
   R

[1]
http://download.oracle.com/javase/1.4.2/docs/api/java/nio/ByteBuffer.html#allocate(int)

**Comment by chirino** [comment]
I'm not talking about using the ByteBuffer.allocate call.  I'm talking about adding a method to MemoryManager:

```
ByteBuffer bb = MemoryManager.allocate(1024*1024);
```

So that I can directly modify the ByteBuffer using Channels to avoid a memory copy..  Compare this to using the MemoryManager store, update, and retrieve calls.  They all force you to work with `byte[]`s so you end up doing a memory copies into and out of direct memory.

**Comment by raffaeleguidi** [comment]
Ok, I finally got it. Basically you would like to create a new ByteBuffer
that calls the slice() method on the allocated buffer and returns it to the
user - this could of course be useful, but a pointer should be created in
any case and added to the list to "reserve" space for it - otherwise it
could be overwritten by other operations. Let's say the method should
return a DirectBufferWithPointer (ok, let's find a better name...)
encapsulating both the pointer and the ByteBuffer, otherwise handling two
return values (the bytebuffer and the pointer) would be problematic

**Comment by raffaeleguidi** [comment]
Sorry, I didn't notice that there were no dots between "ByteBuffer" and "allocate(int size)"... I told you I am getting old! :D Hey, would you mind opening the issue at the project's new home? I stopped working on github since having moved to apache. The issue tracker is: https://issues.apache.org/jira/browse/DIRECTMEMORY - and proposals and contributions are always welcome
