### ISSUE TITLE
Project was closed?

### ISSUE THREAD

**Issue by pugupta-linkedin** [raffaeleguidi/DirectMemory#51]
Hi @raffaeleguidi i noticed the DirectMemory proposal was retired - on the apache wikis.
Hard to track why the project was retired - may i know the reason?

Was there an alternative to this? Was any progress made or could you share any execution plan even if it was not implemented?

Thanks,
Pushkar Gupta

(we're trying to use a offheap cache to store Java objects for our application :))

**Comment by raffaeleguidi** [comment]
Well, back in the days this was needed because no free implementation was available, but due to lack of impulse the project stopped. Good news is that the project stimulated some competition and big names started offering free tiers of commercial implementations and alternatives arrived - see this article for a starting point: https://www.quora.com/Whats-the-best-open-source-solution-for-Java-off-heap-cache

**Comment by pugupta-linkedin** [comment]
Thanks for sharing the thread, taking a deeper look.

My initial study of what's-out-there suggests there are a lot of off-heap solutions but they all need the objects to be deserialized/decoded during access. 

Was hoping to use something that can work with standard Java objects (which are complex - example code generated from Protobuf/Avro schemas). For this - this DirectMemory concept is really good. Basically ask the Garbage collector to not look at this region of memory while being able to use the objects as-is during access.

**Comment by pugupta-linkedin** [comment]
Even though this project was closed, are there any design notes we can use to get inspiration for implementing ourselves? 
(assuming that is non propriety information, ok if it's not)

**Comment by pugupta-linkedin** [comment]
Nvm, sifting through the code in this repo - seems this solution involves encoding objects before storing them in this cache
